2020-05-29 08:15:13,012 ERROR: Exception on /get_intel [GET] [in c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\main\routes_main.py", line 71, in get_intel
    return render_template("get_intel.html", name=name, days=days)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\main\templates\get_intel.html", line 2, in <module>
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\main\templates\get_intel.html", line 17, in root
    <script>
  File "C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\templates\base.html", line 14, in root
    {# three lines in icon #}
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\templates\base.html", line 75, in block_content
  File "C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\main\templates\get_intel.html", line 33, in block_app_content
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_moment.py", line 141, in calendar
    return self._render("calendar()", refresh)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "c:\users\stromel\appdata\local\programs\python\python38\lib\site-packages\flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
AttributeError: 'str' object has no attribute 'strftime'
2020-05-29 08:15:39,520 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:18:01,840 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:23:39,016 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:26:32,395 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:27:17,946 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:29:36,091 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:31:40,906 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:31:45,375 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 08:31:50,641 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Desktop\ohg_plan_parse_new\app\__init__.py:56]
2020-05-29 11:39:55,440 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
2020-05-29 11:52:19,915 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
2020-05-30 11:01:32,913 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
2020-05-30 11:01:52,563 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
2020-05-30 11:18:36,255 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
2020-05-30 11:19:06,451 ERROR: Exception on /new_plan [GET] [in C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Stromel\Data\ohg_plan_parser\app\main\routes_main.py", line 82, in new_plan
    plan = json.loads(request.args.get("plan"))
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
2020-05-30 11:19:49,337 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
2020-05-30 11:21:04,779 ERROR: Exception on /new_plan [GET] [in C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Stromel\Data\ohg_plan_parser\app\main\routes_main.py", line 88, in new_plan
    plan_converted = plan_parser.create_change_objects(json.loads(plan))
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Stromel\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-05-30 11:23:09,778 INFO: ohg_plan_parser startup [in C:\Users\Stromel\Data\ohg_plan_parser\app\__init__.py:56]
